modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="strangeadditions"
version="1.0.0"
displayName="Strange Additions"
displayURL="https://mcreator.net"
credits="Made for the series Strange Horizons!"
authors="Fl4Fold, FearaTheOne"
description="Welcome to Strange Additions! Where all additions are... strange."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.strangeadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration